[package]
name = "client"
version = "0.1.0"
authors = ["Zondax GmbH <info@zondax.ch>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.38"
common = { path = "../common/" }
jsonrpc-http-server = "17.0.0"
jsonrpc_client = { version = "0.5.0", features = ["reqwest"] }
nix = "0.19.1"
raw_sync = "0.1.5"
reqwest = "0.11.0"
scheduler = { path = "../scheduler/" }
serde = { version = "1.0.122", features = ["serde_derive"] }
shared_memory = "0.11.4"
tokio = { version = "1.1.0", features = ["full"] }
tracing = "0.1.22"

[dev-dependencies]
chrono = "0.4.19"
rand = "0.8.2"
