[workspace]
members = [
    "scheduler",
    "client",
    "monitor",
]
exclude = ["monitor"]

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
overflow-checks = true
