[package]
name = "common"
version = "0.1.0"
authors = ["neithanmo <neithanmo@gmail.com>"]
edition = "2018"

[dependencies]
chrono = { version = "0.4.19", features = ["serde"] }
fil-ocl-core = "0.11.4"
num_cpus = "1.13.0"
rust-gpu-tools = "0.3.0"
serde = { version = "1.0.118", features = ["serde_derive"] }
tracing = "0.1.25"
