name: Rust

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install ocl-icd-opencl-dev
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: -- --test-threads 1
        env:
          RUSTFLAGS: --cfg dummy_devices

#  test_mac:
#    name: Test MacOS
#    runs-on: macos-latest
#    steps:
#      - name: Install dependencies
#        run: |
#          brew install bash gcc wget git
#      - uses: actions/checkout@v2
#      - uses: actions-rs/toolchain@v1
#        with:
#          profile: minimal
#          toolchain: stable
#          override: true
#      - uses: actions-rs/cargo@v1
#        with:
#          command: test
#          args: -- --test-threads 1
#        env:
#          RUSTFLAGS: --cfg dummy_devices

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - name: Install opencl
        run: |
          sudo apt-get update
          sudo apt-get install ocl-icd-opencl-dev
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - name: Install opencl
        run: |
          sudo apt-get update
          sudo apt-get install ocl-icd-opencl-dev
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: clippy
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: -- -D warnings
